### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by kindermax** [StarpTech/graphql-registry#22]
**Describe the problem/challenge you have**
First of all, the project is great. Thank you for your work.
My question, do you have any plans to implement web interface?

---

Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by StarpTech** [comment]
Hi @kindermax, this will be definitly addressed in the future. Currently, we are focusing on the right foundation the api. If you have any ideas / use cases you have to cover feel free to document them here.
